// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Candidate is the predicate function for candidate builders.
type Candidate func(*sql.Selector)

// Position is the predicate function for position builders.
type Position func(*sql.Selector)

// Skill is the predicate function for skill builders.
type Skill func(*sql.Selector)
