// Code generated by ent, DO NOT EDIT.

package internal

import (
	"time"

	"github.com/google/uuid"
	"github.com/pulkitbhardwaj/omega/pkgs/ats/internal/candidate"
	"github.com/pulkitbhardwaj/omega/pkgs/ats/internal/position"
	"github.com/pulkitbhardwaj/omega/pkgs/ats/internal/schema"
	"github.com/pulkitbhardwaj/omega/pkgs/ats/internal/skill"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	candidateMixin := schema.Candidate{}.Mixin()
	candidateMixinFields0 := candidateMixin[0].Fields()
	_ = candidateMixinFields0
	candidateFields := schema.Candidate{}.Fields()
	_ = candidateFields
	// candidateDescCreatedAt is the schema descriptor for created_at field.
	candidateDescCreatedAt := candidateMixinFields0[1].Descriptor()
	// candidate.DefaultCreatedAt holds the default value on creation for the created_at field.
	candidate.DefaultCreatedAt = candidateDescCreatedAt.Default.(func() time.Time)
	// candidateDescUpdatedAt is the schema descriptor for updated_at field.
	candidateDescUpdatedAt := candidateMixinFields0[2].Descriptor()
	// candidate.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	candidate.DefaultUpdatedAt = candidateDescUpdatedAt.Default.(func() time.Time)
	// candidate.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	candidate.UpdateDefaultUpdatedAt = candidateDescUpdatedAt.UpdateDefault.(func() time.Time)
	// candidateDescID is the schema descriptor for id field.
	candidateDescID := candidateMixinFields0[0].Descriptor()
	// candidate.DefaultID holds the default value on creation for the id field.
	candidate.DefaultID = candidateDescID.Default.(func() uuid.UUID)
	positionMixin := schema.Position{}.Mixin()
	positionMixinFields0 := positionMixin[0].Fields()
	_ = positionMixinFields0
	positionFields := schema.Position{}.Fields()
	_ = positionFields
	// positionDescCreatedAt is the schema descriptor for created_at field.
	positionDescCreatedAt := positionMixinFields0[1].Descriptor()
	// position.DefaultCreatedAt holds the default value on creation for the created_at field.
	position.DefaultCreatedAt = positionDescCreatedAt.Default.(func() time.Time)
	// positionDescUpdatedAt is the schema descriptor for updated_at field.
	positionDescUpdatedAt := positionMixinFields0[2].Descriptor()
	// position.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	position.DefaultUpdatedAt = positionDescUpdatedAt.Default.(func() time.Time)
	// position.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	position.UpdateDefaultUpdatedAt = positionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// positionDescID is the schema descriptor for id field.
	positionDescID := positionMixinFields0[0].Descriptor()
	// position.DefaultID holds the default value on creation for the id field.
	position.DefaultID = positionDescID.Default.(func() uuid.UUID)
	skillMixin := schema.Skill{}.Mixin()
	skillMixinFields0 := skillMixin[0].Fields()
	_ = skillMixinFields0
	skillFields := schema.Skill{}.Fields()
	_ = skillFields
	// skillDescCreatedAt is the schema descriptor for created_at field.
	skillDescCreatedAt := skillMixinFields0[1].Descriptor()
	// skill.DefaultCreatedAt holds the default value on creation for the created_at field.
	skill.DefaultCreatedAt = skillDescCreatedAt.Default.(func() time.Time)
	// skillDescUpdatedAt is the schema descriptor for updated_at field.
	skillDescUpdatedAt := skillMixinFields0[2].Descriptor()
	// skill.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	skill.DefaultUpdatedAt = skillDescUpdatedAt.Default.(func() time.Time)
	// skill.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	skill.UpdateDefaultUpdatedAt = skillDescUpdatedAt.UpdateDefault.(func() time.Time)
	// skillDescID is the schema descriptor for id field.
	skillDescID := skillMixinFields0[0].Descriptor()
	// skill.DefaultID holds the default value on creation for the id field.
	skill.DefaultID = skillDescID.Default.(func() uuid.UUID)
}
